import { Font } from '@/types/font';

/**
 * Mock 폰트 데이터 (6-8개 샘플)
 * 실제 Supabase 연동 전까지 UI 테스트용으로 사용
 */
export const mockFonts: Font[] = [
    {
        id: '1',
        name: 'Noto Sans KR',
        designer: 'Google Fonts',
        foundry: 'Google',
        downloadUrl: 'https://fonts.google.com/noto/specimen/Noto+Sans+KR',
        officialUrl: 'https://fonts.google.com/noto/specimen/Noto+Sans+KR',
        category: 'gothic',
        license: 'ofl',
        tags: ['한글', '무료', '웹폰트', '깔끔'],
        description: '본고딕은 Adobe와 Google이 주도하여 개발한 오픈소스 글꼴 가족입니다.',
        imageUrls: [],
        thumbnailUrl: 'https://placehold.co/400x300/0D66D0/FFFFFF/png?text=Noto+Sans+KR',
        createdAt: '2024-01-15T10:00:00Z',
        updatedAt: '2024-01-15T10:00:00Z',
        isFavorite: true,
        googleFontsData: {
            family: 'Noto Sans KR',
            variants: ['100', '300', '400', '500', '700', '900'],
            subsets: ['korean', 'latin']
        }
    },
    {
        id: '2',
        name: 'Pretendard',
        designer: '오픈소스 커뮤니티',
        foundry: 'Pretendard',
        downloadUrl: 'https://github.com/orioncactus/pretendard',
        officialUrl: 'https://cactus.tistory.com/306',
        category: 'gothic',
        license: 'ofl',
        tags: ['한글', '무료', '인기', '모던', 'UI'],
        description: '크로스플랫폼 환경에서의 웹폰트 최적화를 위한 가변 폰트입니다.',
        usageNotes: '웹사이트 본문용으로 자주 사용',
        imageUrls: [],
        thumbnailUrl: 'https://placehold.co/400x300/095ABA/FFFFFF/png?text=Pretendard',
        createdAt: '2024-01-10T09:30:00Z',
        updatedAt: '2024-01-10T09:30:00Z',
        isFavorite: true,
    },
    {
        id: '3',
        name: 'Playfair Display',
        designer: 'Claus Eggers Sørensen',
        foundry: 'Google Fonts',
        downloadUrl: 'https://fonts.google.com/specimen/Playfair+Display',
        officialUrl: 'https://fonts.google.com/specimen/Playfair+Display',
        category: 'myeongjo',
        license: 'ofl',
        tags: ['영문', '세리프', '우아함', '고급스러움'],
        description: '18세기 후반의 유럽 계몽주의 시대에서 영감을 얻은 우아한 세리프 글꼴입니다.',
        imageUrls: [],
        thumbnailUrl: 'https://placehold.co/400x300/2C2C2C/FFFFFF/png?text=Playfair+Display',
        createdAt: '2024-01-08T14:20:00Z',
        updatedAt: '2024-01-08T14:20:00Z',
        isFavorite: false,
    },
    {
        id: '4',
        name: 'Montserrat',
        designer: 'Julieta Ulanovsky',
        foundry: 'Google Fonts',
        downloadUrl: 'https://fonts.google.com/specimen/Montserrat',
        officialUrl: 'https://fonts.google.com/specimen/Montserrat',
        category: 'gothic',
        license: 'ofl',
        tags: ['영문', '웹폰트', '기하학적', '인기'],
        description: '부에노스아이레스의 Montserrat 지역의 전통적인 포스터와 사인에서 영감을 받은 글꼴입니다.',
        imageUrls: [],
        thumbnailUrl: 'https://placehold.co/400x300/6E6E6E/FFFFFF/png?text=Montserrat',
        createdAt: '2024-01-05T11:15:00Z',
        updatedAt: '2024-01-05T11:15:00Z',
        isFavorite: false,
    },
    {
        id: '5',
        name: 'Nanum Gothic',
        designer: 'Sandoll Communications',
        foundry: 'Naver',
        downloadUrl: 'https://hangeul.naver.com/font',
        officialUrl: 'https://hangeul.naver.com/font',
        category: 'gothic',
        license: 'ofl',
        tags: ['한글', '무료', '나눔', '고딕'],
        description: '네이버에서 제공하는 대표적인 한글 웹폰트입니다.',
        imageUrls: [],
        thumbnailUrl: 'https://placehold.co/400x300/00C73C/FFFFFF/png?text=Nanum+Gothic',
        createdAt: '2024-01-03T16:45:00Z',
        updatedAt: '2024-01-03T16:45:00Z',
        isFavorite: false,
    },
    {
        id: '6',
        name: 'Roboto',
        designer: 'Christian Robertson',
        foundry: 'Google',
        downloadUrl: 'https://fonts.google.com/specimen/Roboto',
        officialUrl: 'https://fonts.google.com/specimen/Roboto',
        category: 'gothic',
        license: 'apache',
        tags: ['영문', 'Material Design', '인기', '범용'],
        description: 'Google의 Material Design을 위해 개발된 글꼴입니다.',
        imageUrls: [],
        thumbnailUrl: 'https://placehold.co/400x300/4285F4/FFFFFF/png?text=Roboto',
        createdAt: '2024-01-01T08:00:00Z',
        updatedAt: '2024-01-01T08:00:00Z',
        isFavorite: true,
    },
    {
        id: '7',
        name: 'Pacifico',
        designer: 'Vernon Adams',
        foundry: 'Google Fonts',
        downloadUrl: 'https://fonts.google.com/specimen/Pacifico',
        officialUrl: 'https://fonts.google.com/specimen/Pacifico',
        category: 'handwriting',
        license: 'ofl',
        tags: ['영문', '손글씨', '캐주얼', '디스플레이'],
        description: '1950년대 미국 서핑 문화에서 영감을 받은 브러시 스크립트 글꼴입니다.',
        imageUrls: [],
        thumbnailUrl: 'https://placehold.co/400x300/FF6B6B/FFFFFF/png?text=Pacifico',
        createdAt: '2023-12-28T13:30:00Z',
        updatedAt: '2023-12-28T13:30:00Z',
        isFavorite: false,
    },
    {
        id: '8',
        name: 'Bebas Neue',
        designer: 'Ryoichi Tsunekawa',
        foundry: 'Dharma Type',
        downloadUrl: 'https://fonts.google.com/specimen/Bebas+Neue',
        officialUrl: 'https://www.dafont.com/bebas-neue.font',
        category: 'display',
        license: 'ofl',
        tags: ['영문', '굵게', '디스플레이', '타이틀'],
        description: '헤드라인과 제목에 적합한 강렬하고 굵은 산세리프 글꼴입니다.',
        imageUrls: [],
        thumbnailUrl: 'https://placehold.co/400x300/1A1A1A/FFFFFF/png?text=Bebas+Neue',
        createdAt: '2023-12-25T10:00:00Z',
        updatedAt: '2023-12-25T10:00:00Z',
        isFavorite: false,
    },
];

/**
 * 카테고리 필터 옵션 (한글 중심)
 */
export const categoryOptions = [
    { value: 'all', label: '전체' },
    { value: 'gothic', label: '고딕(Sans)' },
    { value: 'myeongjo', label: '명조(Serif)' },
    { value: 'handwriting', label: '손글씨' },
    { value: 'display', label: '디스플레이(Display)' },
    { value: 'dingbat', label: '딩벳' },
    { value: 'other', label: '기타' },
];

/**
 * 정렬 옵션
 */
export const sortOptions = [
    { value: 'latest', label: '최근등록순' },
    { value: 'name', label: '이름순' },
    { value: 'designer', label: '디자이너순' },
];
